import {
  LayoutDashboard,
  Users,
  Calendar,
  HelpCircle,
  LogOut,
  Menu,
  ChevronDown,
  ChevronRight,
  CreditCard,
  UserCircle,
  Building,
  Settings,
  Home,
  PlusCircle,
  Search,
  Filter,
  ArrowUpDown,
  MoreHorizontal,
  Bed,
  DollarSign,
  AlertCircle,
  CheckCircle,
  Clock,
  UserPlus,
  Pencil,
  Trash2,
  Globe,
  Mail,
  MessageSquare,
  Sun,
  Moon,
  ArrowLeft,
  ArrowUpRight,
  ArrowDownLeft,
  AlertTriangle,
  Loader2,
} from "lucide-react"

export const Icons = {
  dashboard: LayoutDashboard,
  users: Users,
  calendar: Calendar,
  helpCircle: HelpCircle,
  logOut: LogOut,
  menu: Menu,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  creditCard: CreditCard,
  userCircle: UserCircle,
  hotel: Building,
  settings: Settings,
  home: Home,
  "plus-circle": PlusCircle,
  search: Search,
  filter: Filter,
  arrowUpDown: ArrowUpDown,
  moreHorizontal: MoreHorizontal,
  bed: Bed,
  users: Users,
  dollarSign: DollarSign,
  alertCircle: AlertCircle,
  checkCircle: CheckCircle,
  clock: Clock,
  userPlus: UserPlus,
  pencil: Pencil,
  trash2: Trash2,
  globe: Globe,
  mail: Mail,
  messageSquare: MessageSquare,
  sun: Sun,
  moon: Moon,
  arrowLeft: ArrowLeft,
  arrowUpRight: ArrowUpRight,
  arrowDownLeft: ArrowDownLeft,
  alertTriangle: AlertTriangle,
  loader2: Loader2,
  // Add other icons here
}

